HOME_CATALOG = [
    {
        "name": "Minimal Living Room",
        "category": "Living Room",
        "style": "Minimal",
        "min_budget": 25000,
        "max_budget": 75000,
        "description": "A clean and simple living room setup with practical furniture and neutral styling.",
        "platform": "IKEA",
        "url": "https://www.ikea.com/",
    },
    {
        "name": "Modern Bedroom",
        "category": "Bedroom",
        "style": "Modern",
        "min_budget": 30000,
        "max_budget": 90000,
        "description": "A modern bedroom setup focused on comfort, storage, and contemporary furniture.",
        "platform": "IKEA",
        "url": "https://www.ikea.com/",
    },
    {
        "name": "Elegant Kitchen Setup",
        "category": "Kitchen",
        "style": "Elegant",
        "min_budget": 50000,
        "max_budget": 150000,
        "description": "A functional kitchen arrangement with elegant storage and modern finishes.",
        "platform": "IKEA",
        "url": "https://www.ikea.com/",
    },
]


PARTY_CATALOG = [
    {
        "name": "Birthday Celebration",
        "event_type": "Birthday",
        "min_budget": 10000,
        "max_budget": 50000,
        "description": "A balanced birthday plan covering food, decoration, cake, and entertainment.",
        "platform": "Swiggy",
        "url": "https://www.swiggy.com/",
    },
    {
        "name": "Wedding Reception",
        "event_type": "Wedding",
        "min_budget": 100000,
        "max_budget": 500000,
        "description": "A reception budget covering catering, decoration, venue requirements, and guest arrangements.",
        "platform": "Zomato",
        "url": "https://www.zomato.com/",
    },
    {
        "name": "Small Get-Together",
        "event_type": "Get-together",
        "min_budget": 5000,
        "max_budget": 25000,
        "description": "A simple gathering plan for food, refreshments, decoration, and basic entertainment.",
        "platform": "Swiggy",
        "url": "https://www.swiggy.com/",
    },
]


JEWELRY_CATALOG = [
    {
        "name": "Classic Gold Necklace",
        "jewelry_type": "Necklace",
        "metal": "Gold",
        "min_budget": 25000,
        "max_budget": 100000,
        "description": "A classic necklace suitable for traditional and formal occasions.",
        "platform": "Amazon",
        "url": "https://www.amazon.in/",
    },
    {
        "name": "Elegant Gold Earrings",
        "jewelry_type": "Earrings",
        "metal": "Gold",
        "min_budget": 10000,
        "max_budget": 50000,
        "description": "Elegant earrings suitable for celebrations and everyday traditional wear.",
        "platform": "Flipkart",
        "url": "https://www.flipkart.com/",
    },
    {
        "name": "Minimal Silver Bracelet",
        "jewelry_type": "Bracelet",
        "metal": "Silver",
        "min_budget": 3000,
        "max_budget": 20000,
        "description": "A lightweight silver bracelet with a simple and modern appearance.",
        "platform": "Amazon",
        "url": "https://www.amazon.in/",
    },
]
SHOPPING_CATALOG = [
    {
        "name": "Modern 3-Seater Sofa",
        "category": "Sofa",
        "price": 28000,
        "platform": "IKEA",
        "description": "A modern sofa suitable for a living room.",
        "url": "https://www.ikea.com/",
    },
    {
        "name": "Study Table",
        "category": "Furniture",
        "price": 12000,
        "platform": "Amazon",
        "description": "A practical study table for home use.",
        "url": "https://www.amazon.in/",
    },
    {
        "name": "Office Chair",
        "category": "Furniture",
        "price": 8500,
        "platform": "Flipkart",
        "description": "An ergonomic chair suitable for study or office use.",
        "url": "https://www.flipkart.com/",
    },
    {
        "name": "Gold Necklace",
        "category": "Jewelry",
        "price": 45000,
        "platform": "Amazon",
        "description": "A classic gold necklace for special occasions.",
        "url": "https://www.amazon.in/",
    },
    {
        "name": "Decorative Party Lights",
        "category": "Party Decoration",
        "price": 1500,
        "platform": "Flipkart",
        "description": "Decorative lights for parties and celebrations.",
        "url": "https://www.flipkart.com/",
    },
    {
        "name": "Dining Table Set",
        "category": "Furniture",
        "price": 35000,
        "platform": "IKEA",
        "description": "A practical dining table set for a home.",
        "url": "https://www.ikea.com/",
    },
    {
        "name": "IKEA Study Desk",
        "category": "Furniture",
        "price": 12000,
        "platform": "IKEA",
        "description": "A simple and functional desk suitable for study or home office use.",
        "url": "https://www.ikea.com/",
    },
    {
        "name": "IKEA Storage Shelf",
        "category": "Furniture",
        "price": 7000,
        "platform": "IKEA",
        "description": "A practical storage shelf for organizing books, decor, and everyday items.",
        "url": "https://www.ikea.com/",
    },
]